[0.038s] Invoking command in '/home/song/steadylab/src/build/zed_topic_benchmark_interfaces': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/song/steadylab/install/yo:/home/song/steadylab/install/steadylab:/opt/ros/foxy CONDA_PROMPT_MODIFIER=(zed) /usr/bin/cmake --build /home/song/steadylab/src/build/zed_topic_benchmark_interfaces -- -j20 -l20
[0.323s] [  9%] Built target zed_topic_benchmark_interfaces__rosidl_generator_c
[0.323s] [ 12%] Built target zed_topic_benchmark_interfaces__cpp
[0.324s] [ 22%] Built target zed_topic_benchmark_interfaces__rosidl_typesupport_c
[0.325s] [ 32%] Built target zed_topic_benchmark_interfaces__rosidl_typesupport_introspection_c
[0.325s] [ 41%] Built target zed_topic_benchmark_interfaces__rosidl_typesupport_fastrtps_cpp
[0.326s] [ 51%] Built target zed_topic_benchmark_interfaces__rosidl_typesupport_cpp
[0.327s] [ 61%] Built target zed_topic_benchmark_interfaces__rosidl_typesupport_introspection_cpp
[0.327s] [ 70%] Built target zed_topic_benchmark_interfaces__rosidl_typesupport_fastrtps_c
[0.327s] [ 70%] Built target zed_topic_benchmark_interfaces
[0.327s] [ 74%] [34m[1mGenerating Python code for ROS interfaces[0m
[0.334s] ImportError in template '/opt/ros/foxy/share/rosidl_generator_py/cmake/../resource/_msg.py.em': 
[0.334s] 
[0.334s] IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
[0.334s] 
[0.334s] Importing the numpy C-extensions failed. This error can happen for
[0.335s] many reasons, often due to issues with your setup or how NumPy was
[0.335s] installed.
[0.335s] 
[0.335s] We have compiled some common reasons and troubleshooting tips at:
[0.335s] 
[0.335s]     https://numpy.org/devdocs/user/troubleshooting-importerror.html
[0.335s] 
[0.336s] Please note and check the following:
[0.336s] 
[0.336s]   * The Python version is: Python3.9 from "/home/song/anaconda3/bin/python3"
[0.336s]   * The NumPy version is: "1.23.1"
[0.336s] 
[0.336s] and make sure that they are the versions you expect.
[0.336s] Please carefully study the documentation linked above for further help.
[0.336s] 
[0.336s] Original error was: No module named 'numpy.core._multiarray_umath'
[0.337s] 
[0.337s] ImportError when expanding '_idl.py.em' into '/home/song/steadylab/src/build/zed_topic_benchmark_interfaces/rosidl_generator_py/zed_topic_benchmark_interfaces/msg/_benchmark_stats_stamped.py': 
[0.337s] 
[0.337s] IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
[0.337s] 
[0.337s] Importing the numpy C-extensions failed. This error can happen for
[0.337s] many reasons, often due to issues with your setup or how NumPy was
[0.337s] installed.
[0.337s] 
[0.338s] We have compiled some common reasons and troubleshooting tips at:
[0.338s] 
[0.338s]     https://numpy.org/devdocs/user/troubleshooting-importerror.html
[0.338s] 
[0.338s] Please note and check the following:
[0.338s] 
[0.338s]   * The Python version is: Python3.9 from "/home/song/anaconda3/bin/python3"
[0.338s]   * The NumPy version is: "1.23.1"
[0.339s] 
[0.339s] and make sure that they are the versions you expect.
[0.339s] Please carefully study the documentation linked above for further help.
[0.339s] 
[0.339s] Original error was: No module named 'numpy.core._multiarray_umath'
[0.339s] 
[0.339s] Error processing idl file: /home/song/steadylab/src/build/zed_topic_benchmark_interfaces/rosidl_adapter/zed_topic_benchmark_interfaces/msg/BenchmarkStatsStamped.idl
[0.339s] Traceback (most recent call last):
[0.339s]   File "/opt/ros/foxy/lib/python3.8/site-packages/numpy/core/__init__.py", line 23, in <module>
[0.340s]     from . import multiarray
[0.340s]   File "/opt/ros/foxy/lib/python3.8/site-packages/numpy/core/multiarray.py", line 10, in <module>
[0.340s]     from . import overrides
[0.340s]   File "/opt/ros/foxy/lib/python3.8/site-packages/numpy/core/overrides.py", line 6, in <module>
[0.340s]     from numpy.core._multiarray_umath import (
[0.340s] ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
[0.340s] 
[0.340s] During handling of the above exception, another exception occurred:
[0.340s] 
[0.340s] Traceback (most recent call last):
[0.340s]   File "/opt/ros/foxy/share/rosidl_generator_py/cmake/../../../lib/rosidl_generator_py/rosidl_generator_py", line 40, in <module>
[0.341s]     sys.exit(main())
[0.342s]   File "/opt/ros/foxy/share/rosidl_generator_py/cmake/../../../lib/rosidl_generator_py/rosidl_generator_py", line 36, in main
[0.342s]     return generate_py(args.generator_arguments_file, args.typesupport_impls.split(';'))
[0.342s]   File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_generator_py/generate_py_impl.py", line 61, in generate_py
[0.343s]     generate_files(generator_arguments_file, mapping)
[0.343s]   File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_cmake/__init__.py", line 96, in generate_files
[0.343s]     raise(e)
[0.343s]   File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_cmake/__init__.py", line 87, in generate_files
[0.343s]     expand_template(
[0.343s]   File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_cmake/__init__.py", line 149, in expand_template
[0.343s]     interpreter.string(template_content, template_path, locals=data)
[0.343s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2391, in string
[0.343s]     self.safe(scanner, True, locals)
[0.343s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2401, in safe
[0.343s]     self.parse(scanner, locals)
[0.343s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2421, in parse
[0.343s]     token.run(self, locals)
[0.344s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 1547, in run
[0.344s]     self.subrun(info[0][1], interpreter, locals)
[0.344s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 1631, in subrun
[0.344s]     token.run(interpreter, locals)
[0.344s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 1425, in run
[0.344s]     interpreter.execute(self.code, locals)
[0.344s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2596, in execute
[0.344s]     _exec(statements, self.globals, locals)
[0.344s]   File "<string>", line 2, in <module>
[0.344s]   File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_cmake/__init__.py", line 198, in _expand_template
[0.344s]     interpreter.string(content, str(template_path), kwargs)
[0.344s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2391, in string
[0.344s]     self.safe(scanner, True, locals)
[0.344s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2401, in safe
[0.345s]     self.parse(scanner, locals)
[0.345s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2421, in parse
[0.345s]     token.run(self, locals)
[0.345s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 1425, in run
[0.345s]     interpreter.execute(self.code, locals)
[0.345s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2596, in execute
[0.345s]     _exec(statements, self.globals, locals)
[0.345s]   File "<string>", line 3, in <module>
[0.345s]   File "/opt/ros/foxy/lib/python3.8/site-packages/numpy/__init__.py", line 140, in <module>
[0.345s]     from . import core
[0.345s]   File "/opt/ros/foxy/lib/python3.8/site-packages/numpy/core/__init__.py", line 49, in <module>
[0.345s]     raise ImportError(msg)
[0.345s] ImportError: 
[0.345s] 
[0.346s] IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
[0.346s] 
[0.346s] Importing the numpy C-extensions failed. This error can happen for
[0.346s] many reasons, often due to issues with your setup or how NumPy was
[0.346s] installed.
[0.346s] 
[0.346s] We have compiled some common reasons and troubleshooting tips at:
[0.346s] 
[0.346s]     https://numpy.org/devdocs/user/troubleshooting-importerror.html
[0.346s] 
[0.346s] Please note and check the following:
[0.346s] 
[0.346s]   * The Python version is: Python3.9 from "/home/song/anaconda3/bin/python3"
[0.346s]   * The NumPy version is: "1.23.1"
[0.347s] 
[0.347s] and make sure that they are the versions you expect.
[0.347s] Please carefully study the documentation linked above for further help.
[0.347s] 
[0.347s] Original error was: No module named 'numpy.core._multiarray_umath'
[0.347s] 
[0.347s] Exception ignored in: <function Interpreter.__del__ at 0x7f76823583a0>
[0.347s] Traceback (most recent call last):
[0.347s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2094, in __del__
[0.347s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2157, in shutdown
[0.347s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2647, in finalize
[0.347s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2200, in push
[0.347s] AttributeError: '_io.TextIOWrapper' object has no attribute 'push'
[0.347s] make[2]: *** [zed_topic_benchmark_interfaces__py/CMakeFiles/zed_topic_benchmark_interfaces__py.dir/build.make:111: rosidl_generator_py/zed_topic_benchmark_interfaces/_zed_topic_benchmark_interfaces_s.ep.rosidl_typesupport_fastrtps_c.c] ì˜¤ë¥˜ 1
[0.348s] make[1]: *** [CMakeFiles/Makefile2:581: zed_topic_benchmark_interfaces__py/CMakeFiles/zed_topic_benchmark_interfaces__py.dir/all] ì˜¤ë¥˜ 2
[0.348s] make: *** [Makefile:141: all] ì˜¤ë¥˜ 2
[0.369s] Invoked command in '/home/song/steadylab/src/build/zed_topic_benchmark_interfaces' returned '2': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/song/steadylab/install/yo:/home/song/steadylab/install/steadylab:/opt/ros/foxy CONDA_PROMPT_MODIFIER=(zed) /usr/bin/cmake --build /home/song/steadylab/src/build/zed_topic_benchmark_interfaces -- -j20 -l20
