[0.037s] Invoking command in '/home/song/steadylab/src/build/zed_topic_benchmark_interfaces': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/song/steadylab/install/yo:/home/song/steadylab/install/steadylab:/opt/ros/foxy CONDA_PROMPT_MODIFIER=(base) /usr/bin/cmake --build /home/song/steadylab/src/build/zed_topic_benchmark_interfaces -- -j20 -l20
[0.222s] [  3%] Built target zed_topic_benchmark_interfaces__cpp
[0.223s] [ 12%] Built target zed_topic_benchmark_interfaces__rosidl_generator_c
[0.223s] [ 22%] Built target zed_topic_benchmark_interfaces__rosidl_typesupport_fastrtps_cpp
[0.223s] [ 38%] Built target zed_topic_benchmark_interfaces__rosidl_typesupport_cpp
[0.223s] [ 41%] Built target zed_topic_benchmark_interfaces__rosidl_typesupport_c
[0.223s] [ 51%] Built target zed_topic_benchmark_interfaces__rosidl_typesupport_introspection_cpp
[0.223s] [ 61%] Built target zed_topic_benchmark_interfaces__rosidl_typesupport_introspection_c
[0.223s] [ 70%] Built target zed_topic_benchmark_interfaces__rosidl_typesupport_fastrtps_c
[0.223s] [ 70%] Built target zed_topic_benchmark_interfaces
[0.223s] [ 74%] [34m[1mGenerating Python code for ROS interfaces[0m
[0.329s] ImportError in template '/opt/ros/foxy/share/rosidl_generator_py/cmake/../resource/_msg.py.em': 
[0.329s] 
[0.330s] IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
[0.330s] 
[0.331s] Importing the numpy C-extensions failed. This error can happen for
[0.331s] many reasons, often due to issues with your setup or how NumPy was
[0.331s] installed.
[0.331s] 
[0.332s] We have compiled some common reasons and troubleshooting tips at:
[0.332s] 
[0.333s]     https://numpy.org/devdocs/user/troubleshooting-importerror.html
[0.333s] 
[0.333s] Please note and check the following:
[0.333s] 
[0.334s]   * The Python version is: Python3.9 from "/home/song/anaconda3/bin/python3"
[0.335s]   * The NumPy version is: "1.23.1"
[0.335s] 
[0.335s] and make sure that they are the versions you expect.
[0.335s] Please carefully study the documentation linked above for further help.
[0.335s] 
[0.335s] Original error was: No module named 'numpy.core._multiarray_umath'
[0.336s] 
[0.336s] ImportError when expanding '_idl.py.em' into '/home/song/steadylab/src/build/zed_topic_benchmark_interfaces/rosidl_generator_py/zed_topic_benchmark_interfaces/msg/_benchmark_stats_stamped.py': 
[0.336s] 
[0.336s] IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
[0.337s] 
[0.338s] Importing the numpy C-extensions failed. This error can happen for
[0.338s] many reasons, often due to issues with your setup or how NumPy was
[0.338s] installed.
[0.339s] 
[0.339s] We have compiled some common reasons and troubleshooting tips at:
[0.341s] 
[0.341s]     https://numpy.org/devdocs/user/troubleshooting-importerror.html
[0.343s] 
[0.343s] Please note and check the following:
[0.343s] 
[0.343s]   * The Python version is: Python3.9 from "/home/song/anaconda3/bin/python3"
[0.344s]   * The NumPy version is: "1.23.1"
[0.344s] 
[0.344s] and make sure that they are the versions you expect.
[0.344s] Please carefully study the documentation linked above for further help.
[0.344s] 
[0.344s] Original error was: No module named 'numpy.core._multiarray_umath'
[0.344s] 
[0.344s] Error processing idl file: /home/song/steadylab/src/build/zed_topic_benchmark_interfaces/rosidl_adapter/zed_topic_benchmark_interfaces/msg/BenchmarkStatsStamped.idl
[0.345s] Traceback (most recent call last):
[0.345s]   File "/opt/ros/foxy/lib/python3.8/site-packages/numpy/core/__init__.py", line 23, in <module>
[0.345s]     from . import multiarray
[0.346s]   File "/opt/ros/foxy/lib/python3.8/site-packages/numpy/core/multiarray.py", line 10, in <module>
[0.346s]     from . import overrides
[0.346s]   File "/opt/ros/foxy/lib/python3.8/site-packages/numpy/core/overrides.py", line 6, in <module>
[0.347s]     from numpy.core._multiarray_umath import (
[0.347s] ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
[0.347s] 
[0.347s] During handling of the above exception, another exception occurred:
[0.348s] 
[0.349s] Traceback (most recent call last):
[0.349s]   File "/opt/ros/foxy/share/rosidl_generator_py/cmake/../../../lib/rosidl_generator_py/rosidl_generator_py", line 40, in <module>
[0.349s]     sys.exit(main())
[0.349s]   File "/opt/ros/foxy/share/rosidl_generator_py/cmake/../../../lib/rosidl_generator_py/rosidl_generator_py", line 36, in main
[0.349s]     return generate_py(args.generator_arguments_file, args.typesupport_impls.split(';'))
[0.350s]   File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_generator_py/generate_py_impl.py", line 61, in generate_py
[0.350s]     generate_files(generator_arguments_file, mapping)
[0.350s]   File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_cmake/__init__.py", line 96, in generate_files
[0.350s]     raise(e)
[0.350s]   File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_cmake/__init__.py", line 87, in generate_files
[0.351s]     expand_template(
[0.351s]   File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_cmake/__init__.py", line 149, in expand_template
[0.351s]     interpreter.string(template_content, template_path, locals=data)
[0.351s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2391, in string
[0.351s]     self.safe(scanner, True, locals)
[0.351s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2401, in safe
[0.353s]     self.parse(scanner, locals)
[0.353s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2421, in parse
[0.353s]     token.run(self, locals)
[0.353s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 1547, in run
[0.353s]     self.subrun(info[0][1], interpreter, locals)
[0.356s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 1631, in subrun
[0.356s]     token.run(interpreter, locals)
[0.356s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 1425, in run
[0.356s]     interpreter.execute(self.code, locals)
[0.357s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2596, in execute
[0.357s]     _exec(statements, self.globals, locals)
[0.357s]   File "<string>", line 2, in <module>
[0.357s]   File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_cmake/__init__.py", line 198, in _expand_template
[0.357s]     interpreter.string(content, str(template_path), kwargs)
[0.357s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2391, in string
[0.357s]     self.safe(scanner, True, locals)
[0.357s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2401, in safe
[0.357s]     self.parse(scanner, locals)
[0.358s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2421, in parse
[0.359s]     token.run(self, locals)
[0.359s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 1425, in run
[0.359s]     interpreter.execute(self.code, locals)
[0.359s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2596, in execute
[0.359s]     _exec(statements, self.globals, locals)
[0.360s]   File "<string>", line 3, in <module>
[0.361s]   File "/opt/ros/foxy/lib/python3.8/site-packages/numpy/__init__.py", line 140, in <module>
[0.361s]     from . import core
[0.361s]   File "/opt/ros/foxy/lib/python3.8/site-packages/numpy/core/__init__.py", line 49, in <module>
[0.361s]     raise ImportError(msg)
[0.361s] ImportError: 
[0.362s] 
[0.362s] IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
[0.362s] 
[0.362s] Importing the numpy C-extensions failed. This error can happen for
[0.363s] many reasons, often due to issues with your setup or how NumPy was
[0.363s] installed.
[0.363s] 
[0.364s] We have compiled some common reasons and troubleshooting tips at:
[0.364s] 
[0.365s]     https://numpy.org/devdocs/user/troubleshooting-importerror.html
[0.367s] 
[0.367s] Please note and check the following:
[0.367s] 
[0.367s]   * The Python version is: Python3.9 from "/home/song/anaconda3/bin/python3"
[0.368s]   * The NumPy version is: "1.23.1"
[0.368s] 
[0.368s] and make sure that they are the versions you expect.
[0.368s] Please carefully study the documentation linked above for further help.
[0.368s] 
[0.368s] Original error was: No module named 'numpy.core._multiarray_umath'
[0.368s] 
[0.369s] Exception ignored in: <function Interpreter.__del__ at 0x7f86d8e9c3a0>
[0.369s] Traceback (most recent call last):
[0.369s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2094, in __del__
[0.369s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2157, in shutdown
[0.370s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2647, in finalize
[0.371s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2200, in push
[0.371s] AttributeError: '_io.TextIOWrapper' object has no attribute 'push'
[0.373s] make[2]: *** [zed_topic_benchmark_interfaces__py/CMakeFiles/zed_topic_benchmark_interfaces__py.dir/build.make:111: rosidl_generator_py/zed_topic_benchmark_interfaces/_zed_topic_benchmark_interfaces_s.ep.rosidl_typesupport_fastrtps_c.c] ì˜¤ë¥˜ 1
[0.373s] make[1]: *** [CMakeFiles/Makefile2:581: zed_topic_benchmark_interfaces__py/CMakeFiles/zed_topic_benchmark_interfaces__py.dir/all] ì˜¤ë¥˜ 2
[0.374s] make: *** [Makefile:141: all] ì˜¤ë¥˜ 2
[0.393s] Invoked command in '/home/song/steadylab/src/build/zed_topic_benchmark_interfaces' returned '2': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/song/steadylab/install/yo:/home/song/steadylab/install/steadylab:/opt/ros/foxy CONDA_PROMPT_MODIFIER=(base) /usr/bin/cmake --build /home/song/steadylab/src/build/zed_topic_benchmark_interfaces -- -j20 -l20
