[0.037s] Invoking command in '/home/song/steadylab/src/build/zed_interfaces': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/song/steadylab/install/yo:/home/song/steadylab/install/steadylab:/opt/ros/foxy CONDA_PROMPT_MODIFIER=(base) /usr/bin/cmake --build /home/song/steadylab/src/build/zed_interfaces -- -j20 -l20
[0.213s] [  0%] Built target zed_interfaces__cpp
[0.214s] [ 12%] Built target zed_interfaces__rosidl_generator_c
[0.215s] [ 24%] Built target zed_interfaces__rosidl_typesupport_cpp
[0.215s] [ 36%] Built target zed_interfaces__rosidl_typesupport_introspection_cpp
[0.216s] [ 48%] Built target zed_interfaces__rosidl_typesupport_c
[0.216s] [ 72%] Built target zed_interfaces__rosidl_typesupport_fastrtps_cpp
[0.216s] [ 72%] Built target zed_interfaces__rosidl_typesupport_introspection_c
[0.217s] [ 84%] Built target zed_interfaces__rosidl_typesupport_fastrtps_c
[0.218s] [ 84%] Built target zed_interfaces
[0.219s] [ 85%] [34m[1mGenerating Python code for ROS interfaces[0m
[0.446s] ImportError in template '/opt/ros/foxy/share/rosidl_generator_py/cmake/../resource/_msg.py.em': 
[0.446s] 
[0.446s] IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
[0.446s] 
[0.446s] Importing the numpy C-extensions failed. This error can happen for
[0.446s] many reasons, often due to issues with your setup or how NumPy was
[0.446s] installed.
[0.446s] 
[0.446s] We have compiled some common reasons and troubleshooting tips at:
[0.446s] 
[0.446s]     https://numpy.org/devdocs/user/troubleshooting-importerror.html
[0.446s] 
[0.446s] Please note and check the following:
[0.446s] 
[0.447s]   * The Python version is: Python3.9 from "/home/song/anaconda3/bin/python3"
[0.447s]   * The NumPy version is: "1.23.1"
[0.447s] 
[0.447s] and make sure that they are the versions you expect.
[0.447s] Please carefully study the documentation linked above for further help.
[0.447s] 
[0.447s] Original error was: No module named 'numpy.core._multiarray_umath'
[0.447s] 
[0.447s] ImportError when expanding '_idl.py.em' into '/home/song/steadylab/src/build/zed_interfaces/rosidl_generator_py/zed_interfaces/msg/_object.py': 
[0.447s] 
[0.447s] IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
[0.447s] 
[0.447s] Importing the numpy C-extensions failed. This error can happen for
[0.447s] many reasons, often due to issues with your setup or how NumPy was
[0.447s] installed.
[0.447s] 
[0.447s] We have compiled some common reasons and troubleshooting tips at:
[0.447s] 
[0.447s]     https://numpy.org/devdocs/user/troubleshooting-importerror.html
[0.447s] 
[0.447s] Please note and check the following:
[0.447s] 
[0.447s]   * The Python version is: Python3.9 from "/home/song/anaconda3/bin/python3"
[0.448s]   * The NumPy version is: "1.23.1"
[0.448s] 
[0.448s] and make sure that they are the versions you expect.
[0.448s] Please carefully study the documentation linked above for further help.
[0.448s] 
[0.448s] Original error was: No module named 'numpy.core._multiarray_umath'
[0.448s] 
[0.448s] Error processing idl file: /home/song/steadylab/src/build/zed_interfaces/rosidl_adapter/zed_interfaces/msg/Object.idl
[0.448s] Traceback (most recent call last):
[0.448s]   File "/opt/ros/foxy/lib/python3.8/site-packages/numpy/core/__init__.py", line 23, in <module>
[0.448s]     from . import multiarray
[0.448s]   File "/opt/ros/foxy/lib/python3.8/site-packages/numpy/core/multiarray.py", line 10, in <module>
[0.448s]     from . import overrides
[0.448s]   File "/opt/ros/foxy/lib/python3.8/site-packages/numpy/core/overrides.py", line 6, in <module>
[0.448s]     from numpy.core._multiarray_umath import (
[0.448s] ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
[0.448s] 
[0.448s] During handling of the above exception, another exception occurred:
[0.448s] 
[0.448s] Traceback (most recent call last):
[0.448s]   File "/opt/ros/foxy/share/rosidl_generator_py/cmake/../../../lib/rosidl_generator_py/rosidl_generator_py", line 40, in <module>
[0.448s]     sys.exit(main())
[0.448s]   File "/opt/ros/foxy/share/rosidl_generator_py/cmake/../../../lib/rosidl_generator_py/rosidl_generator_py", line 36, in main
[0.448s]     return generate_py(args.generator_arguments_file, args.typesupport_impls.split(';'))
[0.448s]   File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_generator_py/generate_py_impl.py", line 61, in generate_py
[0.448s]     generate_files(generator_arguments_file, mapping)
[0.449s]   File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_cmake/__init__.py", line 96, in generate_files
[0.449s]     raise(e)
[0.449s]   File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_cmake/__init__.py", line 87, in generate_files
[0.449s]     expand_template(
[0.449s]   File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_cmake/__init__.py", line 149, in expand_template
[0.449s]     interpreter.string(template_content, template_path, locals=data)
[0.449s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2391, in string
[0.449s]     self.safe(scanner, True, locals)
[0.449s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2401, in safe
[0.449s]     self.parse(scanner, locals)
[0.449s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2421, in parse
[0.449s]     token.run(self, locals)
[0.449s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 1547, in run
[0.449s]     self.subrun(info[0][1], interpreter, locals)
[0.449s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 1631, in subrun
[0.449s]     token.run(interpreter, locals)
[0.449s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 1425, in run
[0.449s]     interpreter.execute(self.code, locals)
[0.449s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2596, in execute
[0.449s]     _exec(statements, self.globals, locals)
[0.449s]   File "<string>", line 2, in <module>
[0.449s]   File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_cmake/__init__.py", line 198, in _expand_template
[0.449s]     interpreter.string(content, str(template_path), kwargs)
[0.449s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2391, in string
[0.449s]     self.safe(scanner, True, locals)
[0.449s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2401, in safe
[0.449s]     self.parse(scanner, locals)
[0.449s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2421, in parse
[0.449s]     token.run(self, locals)
[0.449s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 1425, in run
[0.449s]     interpreter.execute(self.code, locals)
[0.449s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2596, in execute
[0.449s]     _exec(statements, self.globals, locals)
[0.449s]   File "<string>", line 3, in <module>
[0.449s]   File "/opt/ros/foxy/lib/python3.8/site-packages/numpy/__init__.py", line 140, in <module>
[0.449s]     from . import core
[0.450s]   File "/opt/ros/foxy/lib/python3.8/site-packages/numpy/core/__init__.py", line 49, in <module>
[0.450s]     raise ImportError(msg)
[0.450s] ImportError: 
[0.450s] 
[0.450s] IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
[0.450s] 
[0.450s] Importing the numpy C-extensions failed. This error can happen for
[0.450s] many reasons, often due to issues with your setup or how NumPy was
[0.450s] installed.
[0.450s] 
[0.450s] We have compiled some common reasons and troubleshooting tips at:
[0.450s] 
[0.450s]     https://numpy.org/devdocs/user/troubleshooting-importerror.html
[0.450s] 
[0.450s] Please note and check the following:
[0.450s] 
[0.450s]   * The Python version is: Python3.9 from "/home/song/anaconda3/bin/python3"
[0.450s]   * The NumPy version is: "1.23.1"
[0.450s] 
[0.450s] and make sure that they are the versions you expect.
[0.450s] Please carefully study the documentation linked above for further help.
[0.450s] 
[0.450s] Original error was: No module named 'numpy.core._multiarray_umath'
[0.450s] 
[0.456s] Exception ignored in: <function Interpreter.__del__ at 0x7f0ea10123a0>
[0.456s] Traceback (most recent call last):
[0.457s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2094, in __del__
[0.457s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2157, in shutdown
[0.457s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2647, in finalize
[0.457s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2200, in push
[0.457s] AttributeError: '_io.TextIOWrapper' object has no attribute 'push'
[0.462s] make[2]: *** [zed_interfaces__py/CMakeFiles/zed_interfaces__py.dir/build.make:193: rosidl_generator_py/zed_interfaces/_zed_interfaces_s.ep.rosidl_typesupport_fastrtps_c.c] ì˜¤ë¥˜ 1
[0.462s] make[1]: *** [CMakeFiles/Makefile2:581: zed_interfaces__py/CMakeFiles/zed_interfaces__py.dir/all] ì˜¤ë¥˜ 2
[0.462s] make: *** [Makefile:141: all] ì˜¤ë¥˜ 2
