[0.036s] Invoking command in '/home/song/steadylab/src/build/serial_communication': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/song/steadylab/install/yo:/home/song/steadylab/install/steadylab:/opt/ros/foxy CONDA_PROMPT_MODIFIER=(base) /usr/bin/cmake --build /home/song/steadylab/src/build/serial_communication -- -j20 -l20
[0.220s] [  2%] Built target serial_communication__cpp
[0.220s] [ 12%] Built target serial_communication__rosidl_generator_c
[0.220s] [ 23%] Built target serial_communication__rosidl_typesupport_cpp
[0.220s] [ 35%] Built target serial_communication__rosidl_typesupport_introspection_cpp
[0.220s] [ 43%] Built target serial_communication__rosidl_typesupport_introspection_c
[0.220s] [ 53%] Built target serial_communication__rosidl_typesupport_fastrtps_cpp
[0.220s] [ 64%] Built target serial_communication__rosidl_typesupport_c
[0.221s] [ 74%] Built target serial_communication__rosidl_typesupport_fastrtps_c
[0.221s] [ 74%] Built target serial_communication
[0.221s] [ 76%] [34m[1mGenerating Python code for ROS interfaces[0m
[0.277s] ImportError in template '/opt/ros/foxy/share/rosidl_generator_py/cmake/../resource/_msg.py.em': 
[0.278s] 
[0.278s] IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
[0.278s] 
[0.278s] Importing the numpy C-extensions failed. This error can happen for
[0.278s] many reasons, often due to issues with your setup or how NumPy was
[0.279s] installed.
[0.279s] 
[0.279s] We have compiled some common reasons and troubleshooting tips at:
[0.279s] 
[0.279s]     https://numpy.org/devdocs/user/troubleshooting-importerror.html
[0.280s] 
[0.280s] Please note and check the following:
[0.280s] 
[0.281s]   * The Python version is: Python3.9 from "/home/song/anaconda3/bin/python3"
[0.282s]   * The NumPy version is: "1.23.1"
[0.282s] 
[0.282s] and make sure that they are the versions you expect.
[0.282s] Please carefully study the documentation linked above for further help.
[0.283s] 
[0.283s] Original error was: No module named 'numpy.core._multiarray_umath'
[0.284s] 
[0.284s] ImportError when expanding '_idl.py.em' into '/home/song/steadylab/src/build/serial_communication/rosidl_generator_py/serial_communication/msg/_write_car.py': 
[0.284s] 
[0.285s] IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
[0.285s] 
[0.285s] Importing the numpy C-extensions failed. This error can happen for
[0.285s] many reasons, often due to issues with your setup or how NumPy was
[0.285s] installed.
[0.285s] 
[0.285s] We have compiled some common reasons and troubleshooting tips at:
[0.286s] 
[0.286s]     https://numpy.org/devdocs/user/troubleshooting-importerror.html
[0.286s] 
[0.286s] Please note and check the following:
[0.286s] 
[0.286s]   * The Python version is: Python3.9 from "/home/song/anaconda3/bin/python3"
[0.286s]   * The NumPy version is: "1.23.1"
[0.287s] 
[0.287s] and make sure that they are the versions you expect.
[0.287s] Please carefully study the documentation linked above for further help.
[0.287s] 
[0.287s] Original error was: No module named 'numpy.core._multiarray_umath'
[0.289s] 
[0.289s] Error processing idl file: /home/song/steadylab/src/build/serial_communication/rosidl_adapter/serial_communication/msg/WriteCar.idl
[0.290s] Traceback (most recent call last):
[0.290s]   File "/opt/ros/foxy/lib/python3.8/site-packages/numpy/core/__init__.py", line 23, in <module>
[0.290s]     from . import multiarray
[0.290s]   File "/opt/ros/foxy/lib/python3.8/site-packages/numpy/core/multiarray.py", line 10, in <module>
[0.290s]     from . import overrides
[0.290s]   File "/opt/ros/foxy/lib/python3.8/site-packages/numpy/core/overrides.py", line 6, in <module>
[0.290s]     from numpy.core._multiarray_umath import (
[0.291s] ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
[0.291s] 
[0.291s] During handling of the above exception, another exception occurred:
[0.291s] 
[0.291s] Traceback (most recent call last):
[0.292s]   File "/opt/ros/foxy/share/rosidl_generator_py/cmake/../../../lib/rosidl_generator_py/rosidl_generator_py", line 40, in <module>
[0.292s]     sys.exit(main())
[0.292s]   File "/opt/ros/foxy/share/rosidl_generator_py/cmake/../../../lib/rosidl_generator_py/rosidl_generator_py", line 36, in main
[0.293s]     return generate_py(args.generator_arguments_file, args.typesupport_impls.split(';'))
[0.293s]   File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_generator_py/generate_py_impl.py", line 61, in generate_py
[0.293s]     generate_files(generator_arguments_file, mapping)
[0.294s]   File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_cmake/__init__.py", line 96, in generate_files
[0.294s]     raise(e)
[0.294s]   File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_cmake/__init__.py", line 87, in generate_files
[0.294s]     expand_template(
[0.294s]   File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_cmake/__init__.py", line 149, in expand_template
[0.294s]     interpreter.string(template_content, template_path, locals=data)
[0.294s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2391, in string
[0.294s]     self.safe(scanner, True, locals)
[0.294s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2401, in safe
[0.295s]     self.parse(scanner, locals)
[0.296s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2421, in parse
[0.296s]     token.run(self, locals)
[0.296s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 1547, in run
[0.296s]     self.subrun(info[0][1], interpreter, locals)
[0.296s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 1631, in subrun
[0.296s]     token.run(interpreter, locals)
[0.297s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 1425, in run
[0.298s]     interpreter.execute(self.code, locals)
[0.299s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2596, in execute
[0.299s]     _exec(statements, self.globals, locals)
[0.299s]   File "<string>", line 2, in <module>
[0.300s]   File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_cmake/__init__.py", line 198, in _expand_template
[0.300s]     interpreter.string(content, str(template_path), kwargs)
[0.300s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2391, in string
[0.300s]     self.safe(scanner, True, locals)
[0.300s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2401, in safe
[0.300s]     self.parse(scanner, locals)
[0.301s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2421, in parse
[0.301s]     token.run(self, locals)
[0.301s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 1425, in run
[0.301s]     interpreter.execute(self.code, locals)
[0.301s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2596, in execute
[0.301s]     _exec(statements, self.globals, locals)
[0.301s]   File "<string>", line 3, in <module>
[0.301s]   File "/opt/ros/foxy/lib/python3.8/site-packages/numpy/__init__.py", line 140, in <module>
[0.302s]     from . import core
[0.302s]   File "/opt/ros/foxy/lib/python3.8/site-packages/numpy/core/__init__.py", line 49, in <module>
[0.302s]     raise ImportError(msg)
[0.302s] ImportError: 
[0.303s] 
[0.303s] IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
[0.303s] 
[0.303s] Importing the numpy C-extensions failed. This error can happen for
[0.303s] many reasons, often due to issues with your setup or how NumPy was
[0.304s] installed.
[0.304s] 
[0.304s] We have compiled some common reasons and troubleshooting tips at:
[0.304s] 
[0.305s]     https://numpy.org/devdocs/user/troubleshooting-importerror.html
[0.305s] 
[0.305s] Please note and check the following:
[0.305s] 
[0.305s]   * The Python version is: Python3.9 from "/home/song/anaconda3/bin/python3"
[0.305s]   * The NumPy version is: "1.23.1"
[0.305s] 
[0.305s] and make sure that they are the versions you expect.
[0.306s] Please carefully study the documentation linked above for further help.
[0.306s] 
[0.306s] Original error was: No module named 'numpy.core._multiarray_umath'
[0.306s] 
[0.312s] Exception ignored in: <function Interpreter.__del__ at 0x7fe17fd0e3a0>
[0.313s] Traceback (most recent call last):
[0.313s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2094, in __del__
[0.313s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2157, in shutdown
[0.313s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2647, in finalize
[0.313s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2200, in push
[0.313s] AttributeError: '_io.TextIOWrapper' object has no attribute 'push'
[0.319s] make[2]: *** [serial_communication__py/CMakeFiles/serial_communication__py.dir/build.make:82: rosidl_generator_py/serial_communication/_serial_communication_s.ep.rosidl_typesupport_fastrtps_c.c] ì˜¤ë¥˜ 1
[0.320s] make[1]: *** [CMakeFiles/Makefile2:553: serial_communication__py/CMakeFiles/serial_communication__py.dir/all] ì˜¤ë¥˜ 2
[0.322s] make: *** [Makefile:141: all] ì˜¤ë¥˜ 2
[0.378s] Invoked command in '/home/song/steadylab/src/build/serial_communication' returned '2': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/song/steadylab/install/yo:/home/song/steadylab/install/steadylab:/opt/ros/foxy CONDA_PROMPT_MODIFIER=(base) /usr/bin/cmake --build /home/song/steadylab/src/build/serial_communication -- -j20 -l20
